/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedicationsSlugRouteImport } from './routes/medications.$slug'
import { Route as IntakeClinicalRouteImport } from './routes/intake.clinical'

const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsSlugRoute = MedicationsSlugRouteImport.update({
  id: '/medications/$slug',
  path: '/medications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeClinicalRoute = IntakeClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => IntakeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRouteWithChildren
  '/intake/clinical': typeof IntakeClinicalRoute
  '/medications/$slug': typeof MedicationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRouteWithChildren
  '/intake/clinical': typeof IntakeClinicalRoute
  '/medications/$slug': typeof MedicationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intake': typeof IntakeRouteWithChildren
  '/intake/clinical': typeof IntakeClinicalRoute
  '/medications/$slug': typeof MedicationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/intake' | '/intake/clinical' | '/medications/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/intake' | '/intake/clinical' | '/medications/$slug'
  id: '__root__' | '/' | '/intake' | '/intake/clinical' | '/medications/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntakeRoute: typeof IntakeRouteWithChildren
  MedicationsSlugRoute: typeof MedicationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications/$slug': {
      id: '/medications/$slug'
      path: '/medications/$slug'
      fullPath: '/medications/$slug'
      preLoaderRoute: typeof MedicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/clinical': {
      id: '/intake/clinical'
      path: '/clinical'
      fullPath: '/intake/clinical'
      preLoaderRoute: typeof IntakeClinicalRouteImport
      parentRoute: typeof IntakeRoute
    }
  }
}

interface IntakeRouteChildren {
  IntakeClinicalRoute: typeof IntakeClinicalRoute
}

const IntakeRouteChildren: IntakeRouteChildren = {
  IntakeClinicalRoute: IntakeClinicalRoute,
}

const IntakeRouteWithChildren =
  IntakeRoute._addFileChildren(IntakeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntakeRoute: IntakeRouteWithChildren,
  MedicationsSlugRoute: MedicationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
