/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TelehealthConsentRouteImport } from './routes/telehealth-consent'
import { Route as SubscriptionPolicyRouteImport } from './routes/subscription-policy'
import { Route as SafetyInformationRouteImport } from './routes/safety-information'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PharmacyDisclosureRouteImport } from './routes/pharmacy-disclosure'
import { Route as NoticeOfPrivacyPracticesRouteImport } from './routes/notice-of-privacy-practices'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedicationsSlugRouteImport } from './routes/medications.$slug'
import { Route as IntakeClinicalRouteImport } from './routes/intake.clinical'

const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TelehealthConsentRoute = TelehealthConsentRouteImport.update({
  id: '/telehealth-consent',
  path: '/telehealth-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionPolicyRoute = SubscriptionPolicyRouteImport.update({
  id: '/subscription-policy',
  path: '/subscription-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyInformationRoute = SafetyInformationRouteImport.update({
  id: '/safety-information',
  path: '/safety-information',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyDisclosureRoute = PharmacyDisclosureRouteImport.update({
  id: '/pharmacy-disclosure',
  path: '/pharmacy-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeOfPrivacyPracticesRoute =
  NoticeOfPrivacyPracticesRouteImport.update({
    id: '/notice-of-privacy-practices',
    path: '/notice-of-privacy-practices',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsSlugRoute = MedicationsSlugRouteImport.update({
  id: '/medications/$slug',
  path: '/medications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeClinicalRoute = IntakeClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => IntakeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRouteWithChildren
  '/notice-of-privacy-practices': typeof NoticeOfPrivacyPracticesRoute
  '/pharmacy-disclosure': typeof PharmacyDisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safety-information': typeof SafetyInformationRoute
  '/subscription-policy': typeof SubscriptionPolicyRoute
  '/telehealth-consent': typeof TelehealthConsentRoute
  '/terms': typeof TermsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/intake/clinical': typeof IntakeClinicalRoute
  '/medications/$slug': typeof MedicationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRouteWithChildren
  '/notice-of-privacy-practices': typeof NoticeOfPrivacyPracticesRoute
  '/pharmacy-disclosure': typeof PharmacyDisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safety-information': typeof SafetyInformationRoute
  '/subscription-policy': typeof SubscriptionPolicyRoute
  '/telehealth-consent': typeof TelehealthConsentRoute
  '/terms': typeof TermsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/intake/clinical': typeof IntakeClinicalRoute
  '/medications/$slug': typeof MedicationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intake': typeof IntakeRouteWithChildren
  '/notice-of-privacy-practices': typeof NoticeOfPrivacyPracticesRoute
  '/pharmacy-disclosure': typeof PharmacyDisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safety-information': typeof SafetyInformationRoute
  '/subscription-policy': typeof SubscriptionPolicyRoute
  '/telehealth-consent': typeof TelehealthConsentRoute
  '/terms': typeof TermsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/intake/clinical': typeof IntakeClinicalRoute
  '/medications/$slug': typeof MedicationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intake'
    | '/notice-of-privacy-practices'
    | '/pharmacy-disclosure'
    | '/privacy'
    | '/privacy-policy'
    | '/safety-information'
    | '/subscription-policy'
    | '/telehealth-consent'
    | '/terms'
    | '/terms-of-use'
    | '/intake/clinical'
    | '/medications/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intake'
    | '/notice-of-privacy-practices'
    | '/pharmacy-disclosure'
    | '/privacy'
    | '/privacy-policy'
    | '/safety-information'
    | '/subscription-policy'
    | '/telehealth-consent'
    | '/terms'
    | '/terms-of-use'
    | '/intake/clinical'
    | '/medications/$slug'
  id:
    | '__root__'
    | '/'
    | '/intake'
    | '/notice-of-privacy-practices'
    | '/pharmacy-disclosure'
    | '/privacy'
    | '/privacy-policy'
    | '/safety-information'
    | '/subscription-policy'
    | '/telehealth-consent'
    | '/terms'
    | '/terms-of-use'
    | '/intake/clinical'
    | '/medications/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntakeRoute: typeof IntakeRouteWithChildren
  NoticeOfPrivacyPracticesRoute: typeof NoticeOfPrivacyPracticesRoute
  PharmacyDisclosureRoute: typeof PharmacyDisclosureRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SafetyInformationRoute: typeof SafetyInformationRoute
  SubscriptionPolicyRoute: typeof SubscriptionPolicyRoute
  TelehealthConsentRoute: typeof TelehealthConsentRoute
  TermsRoute: typeof TermsRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  MedicationsSlugRoute: typeof MedicationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telehealth-consent': {
      id: '/telehealth-consent'
      path: '/telehealth-consent'
      fullPath: '/telehealth-consent'
      preLoaderRoute: typeof TelehealthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-policy': {
      id: '/subscription-policy'
      path: '/subscription-policy'
      fullPath: '/subscription-policy'
      preLoaderRoute: typeof SubscriptionPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-information': {
      id: '/safety-information'
      path: '/safety-information'
      fullPath: '/safety-information'
      preLoaderRoute: typeof SafetyInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy-disclosure': {
      id: '/pharmacy-disclosure'
      path: '/pharmacy-disclosure'
      fullPath: '/pharmacy-disclosure'
      preLoaderRoute: typeof PharmacyDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice-of-privacy-practices': {
      id: '/notice-of-privacy-practices'
      path: '/notice-of-privacy-practices'
      fullPath: '/notice-of-privacy-practices'
      preLoaderRoute: typeof NoticeOfPrivacyPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications/$slug': {
      id: '/medications/$slug'
      path: '/medications/$slug'
      fullPath: '/medications/$slug'
      preLoaderRoute: typeof MedicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/clinical': {
      id: '/intake/clinical'
      path: '/clinical'
      fullPath: '/intake/clinical'
      preLoaderRoute: typeof IntakeClinicalRouteImport
      parentRoute: typeof IntakeRoute
    }
  }
}

interface IntakeRouteChildren {
  IntakeClinicalRoute: typeof IntakeClinicalRoute
}

const IntakeRouteChildren: IntakeRouteChildren = {
  IntakeClinicalRoute: IntakeClinicalRoute,
}

const IntakeRouteWithChildren =
  IntakeRoute._addFileChildren(IntakeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntakeRoute: IntakeRouteWithChildren,
  NoticeOfPrivacyPracticesRoute: NoticeOfPrivacyPracticesRoute,
  PharmacyDisclosureRoute: PharmacyDisclosureRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SafetyInformationRoute: SafetyInformationRoute,
  SubscriptionPolicyRoute: SubscriptionPolicyRoute,
  TelehealthConsentRoute: TelehealthConsentRoute,
  TermsRoute: TermsRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  MedicationsSlugRoute: MedicationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
